apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  DATABASE_HOST: {{ .Values.config.databaseHost | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}