apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  DATABASE_USERNAME: {{ .Values.secret.databaseUsername | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}